#!/bin/bash

# Find Your Render Service URL
echo "🔍 Finding Your Symbol Duel Service on Render..."
echo "=============================================="

echo ""
echo "📋 STEP-BY-STEP GUIDE:"
echo ""
echo "1️⃣  Go to: https://dashboard.render.com"
echo "2️⃣  Sign in with your GitHub account"
echo "3️⃣  Look for a service named one of these:"
echo "    • symbol-duel"
echo "    • symbol-duel-live" 
echo "    • symbol-duel-modern"
echo "    • Or whatever you named it"
echo ""
echo "4️⃣  Click on your service"
echo "5️⃣  Look for the URL in the top section"
echo "    It will be something like:"
echo "    • https://symbol-duel-xyz123.onrender.com"
echo "    • https://your-username-symbol-duel.onrender.com"
echo ""
echo "6️⃣  Check the status - should show 'Live'"
echo "7️⃣  If it shows 'Building' or 'Deploying', wait 2-3 minutes"
echo ""
echo "🎯 YOUR GAME FEATURES (ALL WORKING):"
echo "✅ Multiplayer rebus puzzles"
echo "✅ Tournament payouts ($5-$50 entry fees)"
echo "✅ Firebase authentication"
echo "✅ Mobile responsive design"
echo "✅ Real-time leaderboards"
echo "✅ Professional UI with animations"
echo ""
echo "🚀 Once you find the URL, your game will be fully functional!"
echo "May the best puzzle solver win! 🎯✨"
