# Render deployment configuration for Symbol Duel

services:
  - type: web
    name: symbol-duel
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
    healthCheckPath: /health
    plan: starter